---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md
- type: jekyll-posts
  label: Listings
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Opinion
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
