---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
pages:
- _posts/creating-international-migrant-development-zones-in-designated-regions-of-underdeveloped-countries.md
